apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: elemental-inventory-pool
  namespace: fleet-default
spec:
  addresses:
    - 192.168.122.150-192.168.122.200
  prefix: 24
  gateway: 192.168.122.1
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: elemental-secondary-pool
  namespace: fleet-default
spec:
  addresses:
    - 172.16.0.150-172.16.0.200
  prefix: 24
  gateway: 172.16.0.1
---
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  namespace: fleet-default
spec:
  machineName: test-${System Information/UUID}
  config:
    network:
      configurator: "nmconnections"
      ipAddresses:
        inventory-ip:
          apiGroup: ipam.cluster.x-k8s.io
          kind: InClusterIPPool
          name: elemental-inventory-pool
        secondary-ip:
          apiGroup: ipam.cluster.x-k8s.io
          kind: InClusterIPPool
          name: elemental-secondary-pool
      config:
        enp1s0: |
          [connection]
          id=Wired connection 1
          type=ethernet
          interface-name=enp1s0
          [ipv4]
          address1={inventory-ip}/24,192.168.1.1
          dns=192.168.122.1;
          method=manual
          route1=0.0.0.0/0,192.168.122.1
          [ipv6]
          method=disabled
        enp8s0: |
          [connection]
          id=Wired connection 2
          type=ethernet
          interface-name=enp8s0
          [ipv4]
          address1={secondary-ip}/24,172.16.0.1
          method=manual
          route1=172.16.0.0/24,172.16.0.1,150
          [ipv6]
          method=disabled
