apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: test-machine
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: password
      # add your custom cloud-config snippets to customize your system
      write_files:
        - content: V2h5IGFyZSB5b3UgY2hlY2tpbmcgdGhpcz8K
          encoding: b64
          path: /etc/custom.file
    elemental:
      install:
        reboot: true
        device: /dev/vda
        iso: https://something.example.com
  machineInventoryLabels:
    clusterName: test
