kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: cluster-machinepools
  namespace: fleet-default
spec:
  rkeConfig:
    machinePools:
      - name: controlPlanePool
        controlPlaneRole: true
        etcdRole: true
        workerRole: false
        quantity: 3
        unhealthyNodeTimeout: 0s
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: selectorControlPlanes
      - name: workersPool
        controlPlaneRole: false
        etcdRole: false
        workerRole: true
        quantity: 1
        unhealthyNodeTimeout: 0s
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: selectorWorkers
  kubernetesVersion: v1.23.7+k3s1
---
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: selectorControlPlanes
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchLabels:
          location: server-room-1
---
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: selectorWorkers
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchLabels:
          location: server-room-2